name: CoolEnchants
version: '${project.version}'
main: enchants.cool.coolenchants.CoolEnchants
api-version: '1.20'
commands:
    CoolEnchants:
        description: Opens the Cool Enchants UI
        usage: /coolenchants
