name: CoolEnchants
version: '${project.version}'
main: enchants.cool.coolenchants.CoolEnchants21
api-version: '1.21'
commands:
    CoolEnchants:
        description: Opens the Cool Enchants UI
        usage: /coolenchants